# Generated by Django 4.2.1 on 2023-05-07 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_remove_task_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
